name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Create 404 page
        run: cp dist/index.html dist/404.html
        
      - name: Add .nojekyll file
        run: touch dist/.nojekyll
        
      - name: Preserve entrance.html
        run: |
          # Keep the original entrance.html and app.html from profile directory
          cp profile/entrance.html dist/entrance.html || cp public/entrance.html dist/entrance.html || echo "Could not find entrance.html"
          cp profile/app.html dist/app.html || cp public/app.html dist/app.html || echo "Could not find app.html"
        
      - name: Create redirect index.html
        run: |
          # Create a simple redirect from index.html to entrance.html
          cat > dist/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="refresh" content="0;url=entrance.html">
            <title>Brian Beadell - Portfolio</title>
            <script>
              window.location.href = "entrance.html";
            </script>
          </head>
          <body>
            <p>Redirecting to Brian Beadell's Portfolio...</p>
          </body>
          </html>
          EOL
        
      - name: Copy files to profile directory
        run: cp -r dist/* profile/
      
      - name: Debug directory contents
        run: |
          echo "Contents of profile directory:"
          ls -la profile/
          echo "Contents of dist directory:"
          ls -la dist/
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add profile
          git commit -m "Update built files in profile directory" || echo "No changes to commit"
          git push 