name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Create 404 page
        run: cp dist/index.html dist/404.html
        
      - name: Add .nojekyll file
        run: touch dist/.nojekyll
        
      - name: Copy files to profile directory
        run: cp -r dist/* profile/
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add profile
          git commit -m "Update built files in profile directory" || echo "No changes to commit"
          git push 